### PR TITLE
Fix documentation + Added alternate way to auth for docker

### PR DESCRIPTION
**Pull request by mpiorowski**

### CODE REVIEW

**Comment by mpiorowski** [comment]
Fix #4

**Comment by sethvargo** [comment]
Hi @mpiorowski 

Are you tagging images with a github SHA or are you pushing images named a GitHub SHA? The `:` indicates which label to use.

**Comment by mpiorowski** [comment]
@sethvargo The thing is, that the `:` was just not working (so the tag name). To be truthfully, i was writing this github action 1-2 months ago, so maybe something changes by that day. But right now, with `/` everything still works perfectly.

**Comment by sethvargo** [comment]
Hi @mpiorowski 

It depends on your repo layout. If you've created container images that are _named_ the GitHub SHA, then you need to slash. If you are creating container images _named_ $SERVICE and then _tagging_ them with the GitHub SHA, you need the colon. The preferred approach in the community is to use tags, so I believe the example workflow is correct.

**Comment by mpiorowski** [comment]
@sethvargo First of all, thanks for quick replies :)

So i checked the deploy with the initial setup, and the error i get is:
name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE

And it seems right, cos right now we are ending our image url on REPOSITORY.

So maybe we should suggest the follwoing url? :

`${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}`

**Comment by sethvargo** [comment]
Yea, it should be:

```text
LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
```

@verbanicm

**Comment by mpiorowski** [comment]
Updated pr with the new url's

**Review by sethvargo — APPROVED** [review]

**Pull request merged**
